dist: xenial
language: java

before_script:
  - pip install --upgrade pip;
    pip install --user ansible==2.1.1.0;
    pip install --user html5validator;
    pip install --user robotframework-lint;

script:
  - html5validator --version || true
  - rflint --version || true
  - echo 'FINISH'

jdk:
  - openjdk8

services:
  - mysql

branches:
  except:
  - /^(re|old)_.*$/

notifications:
  email:
    on_success: always # default: change
    on_failure: always # default: always

# We don't want to run `mvn install -DskipTests=true` for downloading project's dependencies
install: true
